- php5.6-fpm/docker-entrypoint.sh
- php7.0-fpm/docker-entrypoint.sh
- php7.2-fpm/docker-entrypoint.sh
- php7.3-fpm/docker-entrypoint.sh
- templates/ddbcms/docker-compose.yml
- templates/drupal-7/docker-compose.yml
- templates/drupal-8/docker-compose.yml
- templates/ereolen/docker-compose.yml
- templates/symfony-3/docker-compose.yml
- templates/symfony-4/docker-compose.yml
Add docker host domain to `/etc/hosts` file in `phpfpm` containers.
> Added DOCKER_HOST_DOMAIN

- scripts/itkdev-docker-compose
Makes it easier to get the url of a specific service.
> Added service and port options to url command

- scripts/itkdev-docker-compose
See https://github.com/TablePlus/TablePlus/issues/227
> Added sql:open command as shortcut to open tableplus or other DB GUI

- completion/zsh/_itkdev-docker-compose
- scripts/itkdev-docker-compose
- templates/aakbcms/docker-compose.yml
- templates/ddbcms/docker-compose.yml
- templates/drupal-7/docker-compose.yml
- templates/drupal-8/docker-compose.yml
- templates/drupal-9/docker-compose.yml
- templates/ereolen/docker-compose.yml
- templates/symfony-3/docker-compose.yml
- templates/symfony-4/docker-compose.yml
- Fixed typos
- Added check for argument
> Fix typos and bugs

- README.md
- completion/bash/itkdev-docker-compose-completion.bash
- completion/zsh/_itkdev-docker-compose
- scripts/itkdev-docker-compose
- templates/aakbcms/docker-compose.yml
- templates/ddbcms/docker-compose.yml
- templates/drupal-7/docker-compose.yml
- templates/drupal-8/docker-compose.yml
- templates/drupal-9/docker-compose.yml
- templates/ereolen/docker-compose.yml
- templates/symfony-3/docker-compose.yml
- templates/symfony-4/docker-compose.yml
Note: that this requires all are using NFS shares (if docker-compose.yml have it enabled). So this requires information for the whole team before being released
> Added nfs support and version command

- templates/aakbcms/docker-compose.yml
- templates/ddbcms/docker-compose.yml
- templates/drupal-7/docker-compose.yml
- templates/drupal-8/docker-compose.yml
- templates/drupal-9/docker-compose.yml
- templates/ereolen/docker-compose.yml
- templates/symfony-3/docker-compose.yml
- templates/symfony-4/docker-compose.yml
Adds label to database containers for easy use with https://symfony.com/doc/current/setup/symfony_server.html#docker-integration.
> Add database container labels

- images/itkdev.pub
- images/mailhog/Dockerfile
- templates/aakbcms/docker-compose.yml
- templates/ddbcms/docker-compose.yml
- templates/drupal-7/docker-compose.dev.yml
- templates/drupal-7/docker-compose.yml
- templates/drupal-8/docker-compose.dev.yml
- templates/drupal-8/docker-compose.yml
- templates/drupal-9/docker-compose.dev.yml
- templates/drupal-9/docker-compose.yml
- templates/ereolen/docker-compose.yml
- templates/symfony-3/docker-compose.dev.yml
- templates/symfony-3/docker-compose.yml
- templates/symfony-4/docker-compose.dev.yml
- templates/symfony-4/docker-compose.yml
- templates/symfony-6/docker-compose.dev.yml
- templates/symfony-6/docker-compose.yml
* Mailhog's own docker container have not been maintained for 2 years
* Also we the mailhog/mailhog image is not signed
> ItkDev mailhog

- completion/bash/itkdev-docker-compose-completion.bash
- completion/zsh/_itkdev-docker-compose
- scripts/itkdev-docker-compose
Makes it easy to run php inside phpfpm container:
```sh
itkdev-docker-compose php
```
> Added php command

- scripts/itkdev-docker-compose
Changes `docker-compose` (the command) to `docker compose`.
> Changed “docker-compose” to “docker compose”

- images/php8.0-fpm/alpine/etc/php/php.ini
https://jira.itkdev.dk/browse/SUPP0RT-816
> Added missing sendmail_path in PHP settings

- templates/aakbcms/.docker/nginx.conf
- templates/aakbcms/.docker/vhost.conf
- templates/aakbcms/docker-compose.yml
- templates/ddbcms/.docker/nginx.conf
- templates/ddbcms/.docker/vhost.conf
- templates/ddbcms/docker-compose.yml
- templates/drupal-7/.docker/nginx.conf
- templates/drupal-7/.docker/vhost.conf
- templates/drupal-7/docker-compose.server.yml
- templates/drupal-8/.docker/nginx.conf
- templates/drupal-8/.docker/vhost.conf
- templates/drupal-8/docker-compose.server.yml
- templates/drupal-9/.docker/nginx.conf
- templates/drupal-9/.docker/vhost.conf
- templates/drupal-9/docker-compose.server.yml
- templates/ereolen/.docker/nginx.conf
- templates/ereolen/.docker/vhost.conf
- templates/ereolen/docker-compose.yml
- templates/symfony-3/.docker/nginx.conf
- templates/symfony-3/.docker/vhost.conf
- templates/symfony-3/docker-compose.server.yml
- templates/symfony-4/.docker/nginx.conf
- templates/symfony-4/.docker/vhost.conf
- templates/symfony-4/docker-compose.server.yml
- templates/symfony-6/.docker/nginx.conf
- templates/symfony-6/.docker/vhost.conf
- templates/symfony-6/docker-compose.server.yml
Ticket: https://jira.itkdev.dk/browse/SERV-624
> Updated nginx config with better logging of real ip

- templates/aakbcms/.docker/vhost.conf
- templates/aakbcms/docker-compose.yml
- templates/ddbcms/.docker/vhost.conf
- templates/ddbcms/docker-compose.yml
- templates/drupal-7/.docker/vhost.conf
- templates/drupal-7/docker-compose.dev.yml
- templates/drupal-7/docker-compose.redirect.yml
- templates/drupal-7/docker-compose.server.yml
- templates/drupal-7/docker-compose.yml
- templates/drupal-8/.docker/vhost.conf
- templates/drupal-8/docker-compose.dev.yml
- templates/drupal-8/docker-compose.redirect.yml
- templates/drupal-8/docker-compose.server.yml
- templates/drupal-8/docker-compose.yml
- templates/drupal-9/.docker/vhost.conf
- templates/drupal-9/docker-compose.dev.yml
- templates/drupal-9/docker-compose.redirect.yml
- templates/drupal-9/docker-compose.server.yml
- templates/drupal-9/docker-compose.yml
Search the interweb and found this solution...
> LIT-350: Add index.php redirect to nginx

- traefik/docker-compose.yml
> Upgrade traefik from 2.6 to 2.9

- templates/drupal-7/docker-compose.dev.yml
- templates/drupal-8/docker-compose.dev.yml
- templates/drupal-9/docker-compose.dev.yml
- templates/symfony-3/docker-compose.dev.yml
- templates/symfony-4/docker-compose.dev.yml
- templates/symfony-6/docker-compose.dev.yml
Adds `restart: unless-stopped` to mailhog service in server dev setup.
> Added restart: unless-stopped to mailhog dev server service

- scripts/itkdev-docker-compose
Updates information on using Xdebug in PHPStorm. Adds information on how to use Xdebug in VS Code.
> Updated information on using Xdebug

- completion/bash/itkdev-docker-compose-completion.bash
- completion/zsh/_itkdev-docker-compose
- scripts/itkdev-docker-compose
Adds a simple `self:update` command that updates with the latest changes in [develop](https://github.com/itk-dev/devops_itkdev-docker/tree/develop) unless local changes have been made.
> Added self:update command

- completion/bash/itkdev-docker-compose-completion.bash
- completion/zsh/_itkdev-docker-compose
- scripts/itkdev-docker-compose
> Added sql:log command

- scripts/itkdev-docker-compose
Allows using custom compose file (default: `docker-compose.yml`) by setting `COMPOSE_FILE` environment variable.
> Handled custom compose file

- scripts/itkdev-docker-compose
https://leantime.itkdev.dk/?tab=timesheet#/tickets/showTicket/1532
* Updates `tput` options
> Update tput options

- templates/drupal-10/.docker/nginx.conf
- templates/drupal-10/.docker/templates/default.conf.template
- templates/drupal-7/.docker/nginx.conf
- templates/drupal-7/.docker/templates/default.conf.template
- templates/drupal-8/.docker/nginx.conf
- templates/drupal-8/.docker/templates/default.conf.template
- templates/drupal-9/.docker/nginx.conf
- templates/drupal-9/.docker/templates/default.conf.template
- templates/symfony-3/.docker/nginx.conf
- templates/symfony-3/.docker/templates/default.conf.template
- templates/symfony-4/.docker/nginx.conf
- templates/symfony-4/.docker/templates/default.conf.template
- templates/symfony-6/.docker/nginx.conf
- templates/symfony-6/.docker/templates/default.conf.template
https://leantime.itkdev.dk/dashboard/home#/tickets/showTicket/2167
> 2167: Fixed correct IP in nginx logs

- CHANGELOG.md
- templates/drupal-10/docker-compose.server.yml
- templates/drupal-10/docker-compose.yml
- templates/drupal-9/docker-compose.server.yml
- templates/drupal-9/docker-compose.yml
- templates/symfony-6/docker-compose.server.yml
- templates/symfony-6/docker-compose.yml
> Update to PHP 8.3
